AutoQuestionGenerator/AutoQuestionGenerator/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoQuestionGenerator.Models
{
    public class LoginViewModel
    {
        public string Organisation { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Error { get; set; }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoQuestionGenerator.Accounts;
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutoQuestionGenerator.Controllers
{
    public class UserController : Controller
    {
        public UserController()
        {
        }

        public IActionResult Delete(int id)
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel user, string returnUrl)
        {
            var DbOrganisation = DatabaseConnector.Get<Organisations>().FirstOrDefault(x => x.Organisation_Username == user.Organisation);
            if (!ModelState.IsValid || DbOrganisation == null)
            {
                if (DbOrganisation == null)
                {
                    user.Error = "Organisation does not exist.";
                    return View(user);
                }
                return View(user);
            }
            var DbUser = UserHelper.GetUser(user.Username, DbOrganisation.OrganisationID);
            if (DbUser == null)
            {
                user.Error = "Username or password incorrect.";
                return View(user);
            }

            if (DbUser.OrganisationID != DbOrganisation.OrganisationID)
            {
                user.Error = "Organisation is incorrect";
                return View(user);
            }

            if (Hasher.ValidatePassword(user.Password, DbUser.Password))
            {
                HttpContext.Session.Set("OrgId", Encoding.UTF8.GetBytes(DbOrganisation.OrganisationID.ToString()));
                HttpContext.Session.Set("Org_Uname", Encoding.UTF8.GetBytes(DbOrganisation.Organisation_Name));
                HttpContext.Session.Set(UserHelper.SESSION_UID, Encoding.UTF8.GetBytes(DbUser.UserID.ToString()));
                HttpContext.Session.Set("Username", Encoding.UTF8.GetBytes(user.Username));
                DbUser.Last_Logged_In = DateTime.Now;
                DatabaseConnector.Update(DbUser);
                DatabaseConnector.PushChanges();
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                user.Error = "Username or password incorrect.";
                return View(user);
            }
        }

        public IActionResult Logout(string returnUrl)
        {
            UserHelper.LogOut(HttpContext.Session);
            OrganisationHelper.LogOut(HttpContext.Session);
            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Lost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Lost(LoginViewModel user)
        {
            var DbOrganisation = DatabaseConnector.Get<Organisations>().FirstOrDefault(x => x.Organisation_Username == user.Organisation);
            if (!ModelState.IsValid || DbOrganisation == null)
            {
                return View(user);
            }
            var DbUser = UserHelper.GetUser(user.Username, DbOrganisation.OrganisationID);

            if (!ModelState.IsValid || DbUser == null) return View(user);

            DbUser.Password = Hasher.Hash(user.Password);
            DatabaseConnector.Update(DbUser);
            DatabaseConnector.PushChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.Accounts;
using Microsoft.AspNetCore.Mvc;
using AutoQuestionGenerator.Models;
using AutoQuestionGenerator.Helper;

namespace AutoQuestionGenerator.Controllers
{
    [Authorized]
    public class WorkController : Controller
    {
        IdentityModels _context;

        public WorkController()
        {
            _context = new IdentityModels();
        }

        public IActionResult Index()
        {
            var user = UserHelper.GetUserId(HttpContext.Session);

            var groups = _context.groupUsers.Where(x => x.UserID == user).Select(x => x.GroupID).ToArray();

            List<WorksetViewModel> viewModels = new List<WorksetViewModel>();
            foreach(var group in groups)
            {
                var sets = _context.worksets.Where(x => x.GroupID == group).ToArray();

                foreach (var set in sets)
                {
                    if(_context.questionSets.FirstOrDefault(x => x.WorkSetID == set.WorksetID && x.UserID == user) == null)
                    {
                        var setBy = _context.users.FirstOrDefault(x => x.UserID == set.SetBy);
                        viewModels.Add(new WorksetViewModel()
                        {
                            WorksetID = set.WorksetID,
                            WorksetName = set.WorksetName,
                            Time_Allowed = set.Time_Allowed,
                            Date_Due = set.Date_Due,
                            Date_Set = set.Date_Set,
                            SetBy = setBy.First_Name + " " + setBy.Last_Name,
                            Group_Name = _context.groups.FirstOrDefault(x => x.GroupID == group).Group_Name,
                            SetType = _context.worktype.FirstOrDefault(x => x.SetType_ID == set.SetType).SetType_Name,
                            RandomOrdering = set.RandomOrdering,
                            ExamStyle = set.ExamStyle
                        });
                    }
                }
            }

            return View(viewModels.ToArray());
        }

        public IActionResult Assign(int setID)
        {
            var saved = _context.worksets.FirstOrDefault(x => x.WorksetID == setID);
            var model = new CreateSetViewModel()
            {
                TimeAllowed = saved.Time_Allowed,
                RandomQuestions = saved.RandomOrdering,
                Groups = UserHelper.GetGroups(UserHelper.GetUserId(HttpContext.Session)),
                SetType = saved.SetType
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Assign(CreateSetViewModel model)
        {
            Worksets sets = new Worksets()
            {
                GroupID = model.GroupID,
                WorksetName = model.WorksetName,
                SetBy = UserHelper.GetUserId(HttpContext.Session),
                Time_Allowed = model.TimeAllowed,
                Date_Set = DateTime.Now.Date,
                SetType = model.SetType,
                Date_Due = model.Date_Due,
                ExamStyle = model.SelectFromList,
                RandomOrdering = model.RandomQuestions
            };

            return RedirectToAction("Set");
        }

        public IActionResult Set()
        {
            var sets = _context.worksets.Where(x => x.SetBy == UserHelper.GetUserId(HttpContext.Session) && x.GroupID != null).ToList();
            List<WorksetViewModel> workset = new List<WorksetViewModel>();
            foreach (var set in sets)
            {
                workset.Add(new WorksetViewModel()
                {
                    WorksetID = set.WorksetID,
                    WorksetName = set.WorksetName,
                    Time_Allowed = set.Time_Allowed,
                    SetType = _context.worktype.FirstOrDefault(x => x.SetType_ID == set.SetType).SetType_Name,
                    Date_Set = set.Date_Set,
                    Date_Due = set.Date_Due,
                    Group_Name = _context.groups.FirstOrDefault(x => x.GroupID == set.GroupID).Group_Name,
                    ExamStyle = set.ExamStyle,
                    RandomOrdering = set.RandomOrdering
                });
            }

            return View(workset.ToArray());
        }

        public IActionResult Later()
        {
            var sets = _context.worksets.Where(x => x.SetBy == UserHelper.GetUserId(HttpContext.Session) && x.GroupID == null).ToList();
            List<WorksetViewModel> workset = new List<WorksetViewModel>();
            foreach (var set in sets)
            {
                workset.Add(new WorksetViewModel()
                {
                    WorksetID = set.WorksetID,
                    WorksetName = set.WorksetName,
                    Time_Allowed = set.Time_Allowed,
                    SetType = _context.worktype.FirstOrDefault(x => x.SetType_ID == set.SetType).SetType_Name,
                    Date_Set = set.Date_Set,
                    Date_Due = set.Date_Due,
                    ExamStyle = set.ExamStyle,
                    RandomOrdering = set.RandomOrdering
                });
            }

            return View(workset.ToArray());
        }

        public IActionResult Workset(int id)
        {
            if (UserHelper.UserHasBasicAccess(UserHelper.GetUserId(HttpContext.Session), id, _context))
            {
                List<WorkViewModel> viewModel = new List<WorkViewModel>();
                var work = _context.work.Where(x => x.WorkSetID == id).ToList();

                foreach (var piece in work)
                {
                    viewModel.Add(new WorkViewModel()
                    {
                        WorkID = piece.WorkID,
                        WorkSetName = _context.worksets.FirstOrDefault(x => x.WorksetID == id).WorksetName,
                        Seed = piece.Seed,
                        QuestionType = _context.questionTypes.FirstOrDefault(x => x.TypeID == piece.QuestionType).Type_Name
                    });
                }

                return View(viewModel.ToArray());
            }
            return Unauthorized();
        }

        public PartialViewResult UpdateWork(int updateID)
        {
            var user = UserHelper.GetUserId(HttpContext.Session);

            List<WorksetViewModel> viewModels = new List<WorksetViewModel>();

            var groups = _context.groupUsers.Where(x => x.UserID == user).Select(x => x.GroupID).ToArray();
            foreach (var group in groups)
            {
                var sets = _context.worksets.Where(x => x.GroupID == group).ToArray();

                foreach (var set in sets)
                {
                    bool add = false;
                    switch (updateID)
                    {
                        case 1:
                            if (_context.questionSets.FirstOrDefault(x => x.WorkSetID == set.WorksetID && x.UserID == user) == null && set.Date_Due >= DateTime.Now.Date)
                                add = true;
                            break;
                        case 2:
                            if (_context.questionSets.FirstOrDefault(x => x.WorkSetID == set.WorksetID && x.UserID == user) == null && set.Date_Due <= DateTime.Now.Date)
                                add = true;
                            break;
                        case 3:
                            if (_context.questionSets.FirstOrDefault(x => x.WorkSetID == set.WorksetID && x.UserID == user) != null && set.Date_Due >= DateTime.Now.Date)
                                add = true;
                            break;
                    }
                    if (add)
                    {
                        var setBy = _context.users.FirstOrDefault(x => x.UserID == set.SetBy);
                        viewModels.Add(new WorksetViewModel()
                        {
                            WorksetID = set.WorksetID,
                            WorksetName = set.WorksetName,
                            Time_Allowed = set.Time_Allowed,
                            Date_Due = set.Date_Due,
                            Date_Set = set.Date_Set,
                            SetBy = setBy.First_Name + " " + setBy.Last_Name,
                            Group_Name = _context.groups.FirstOrDefault(x => x.GroupID == group).Group_Name,
                            SetType = _context.worktype.FirstOrDefault(x => x.SetType_ID == set.SetType).SetType_Name,
                            RandomOrdering = set.RandomOrdering,
                            ExamStyle = set.ExamStyle
                        });
                    }
                }
            }

            return PartialView("_currentWorkTable", viewModels.ToArray());
        }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoQuestionGenerator</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/js/jquery.min.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/chartjs/utils.js" asp-append-version="true"></script>
        <script src="~/lib/chartjs/Chart.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/jquery.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/chartjs/utils.js" asp-append-version="true"></script>
        <script src="~/lib/chartjs/Chart.min.js" asp-append-version="true"
                asp-fallback-src="~/lib/chartjs/Chart.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AutoQuestionGenerator</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @{ byte[] uid; HttpContextAccessor.HttpContext.Session.TryGetValue(AutoQuestionGenerator.Accounts.UserHelper.SESSION_UID, out uid);
                        bool teacher = AutoQuestionGenerator.Accounts.UserHelper.UserInRole(uid, AutoQuestionGenerator.Accounts.UserHelper.ROLE_TEACHER, new AutoQuestionGenerator.DatabaseModels.IdentityModels()); }
                    <li><a asp-area="" asp-controller="Work" asp-action="@(teacher ? "Set" : "Index")">Work@(teacher ? " Set" : " to Do")</a></li>
                    @if (teacher)
                    {
                        <li><a asp-area="" asp-controller="Work" asp-action="Later">Saved for Later</a></li>
                        <li><a asp-area="" asp-controller="Set" asp-action="Create">Create Workset</a></li>
                    }
                </ul>
                <partial name="_Login" />
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 to @DateTime.Now.Year - AutoQuestionGenerator</p>
        </footer>
    </div>
    <partial name="_ValidationScriptsPartial.cshtml" />
</body>
</html>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Shared/_Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<ul class="nav navbar-nav navbar-right">
    @{byte[] username, orgUname; }
    @if (HttpContextAccessor.HttpContext.Session.TryGetValue("Username", out username))
    {
        <li><a asp-area="" asp-controller="Account" asp-action="Index">Welcome @System.Text.Encoding.UTF8.GetString(username)!</a></li>
        @if (HttpContextAccessor.HttpContext.Session.TryGetValue("Org_Uname", out orgUname))
        {
            <li style="overflow:hidden;"><a asp-area="" asp-controller="Organisation" asp-action="Index">Of  @System.Text.Encoding.UTF8.GetString(orgUname)!</a></li>
            <li><a asp-area="" asp-controller="User" asp-action="Logout">Logout</a></li>
        }
    }
    else
    {
        <li><a asp-area="" asp-controller="User" asp-action="Login">Login</a></li>
    }
</ul>