AutoQuestionGenerator/AutoQuestionGenerator/Models/BuildViewModel.cs
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.QuestionModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoQuestionGenerator.Models
{
    public class BuildViewModel
    {
        public int WorkSetID { get; set; }
        public WorkPartial[] Work { get; set; }
        public CreatedWork createdWork { get; set; }
    }

    public class WorkPartial
    {
        public string TypeName { get; set; }
        public int TypeID { get; set; }
        public int Seed { get; set; }
        public string Answer { get; set; }
    }

    public class CreatedWork
    {
        public bool SelectFromList { get; set; }
        public CatagoryTypes[] CatagoryTypes { get; set; }
    }

    public class CatagoryTypes
    {
        public string CatTypeName { get; set; }
        public LengthCatagory[] Catagories { get; set; }
    }

    public class LengthCatagory
    {
        public string catagoryName { get; set; }
        public TypedWork[] WorkTypes { get; set; }
    }

    public class TypedWork
    {
        public int TypeID { get; set; }
        public string WorkType { get; set; }
        public WorkPartial[] PossibleWork { get; set; }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Models/WorksetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoQuestionGenerator.Models
{
    public class WorksetViewModel
    {
        public int WorksetID { get; set; }
        public string WorksetName { get; set; }
        public string Group_Name { get; set; }
        public string SetBy { get; set; }
        public string SetType { get; set; }
        public int Time_Allowed { get; set; }
        public bool ExamStyle { get; set; }
        public bool RandomOrdering { get; set; }
        public DateTime Date_Set { get; set; }
        public DateTime Date_Due { get; set; }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.Accounts;

namespace AutoQuestionGenerator.Controllers
{
    [Authorized]
    public class QuestionController : Controller
    {

        public QuestionController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Controllers/SetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoQuestionGenerator.Accounts;
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.Models;
using AutoQuestionGenerator.QuestionModels;
using AutoQuestionGenerator.QuestionModels.Interpreter;
using AutoQuestionGenerator.Helper;
using Microsoft.AspNetCore.Mvc;

namespace AutoQuestionGenerator.Controllers
{
    [Authorized]
    public class SetController : Controller
    {
        PythonInterpreter Interpreter;

        /// <summary>
        /// When the controller is loaded generate a new python interpreter.
        /// </summary>
        public SetController()
        {
            Interpreter = new PythonInterpreter();
        }

        // Uses a method to convert a workset to a PDF
        public IActionResult Print(int setID)
        {
            var set = DatabaseConnector.GetWorkset(setID);
            var path = set.ToPDF();
            return LocalRedirect("~" + path);
        }

        /// <summary>
        /// Return the index page for viewing the workset
        /// however the index is the page used to complete a workset
        /// so this file also sets up all the questions and 
        /// questionset information and it then saves this.
        /// </summary>
        /// <param name="WorkSetID"></param>
        /// <returns></returns>
        public IActionResult Index(int WorkSetID)
        {
            int uid = UserHelper.GetUserId(HttpContext.Session);

            // Checks whether the user can access and therefore complete the workset
            // If they can set it up.
            if (UserHelper.UserHasBasicAccess(uid, WorkSetID))
            {
                var set = DatabaseConnector.GetWorkset(WorkSetID);

                if (set == null)
                {
                    return RedirectToAction("Index", "Work");
                }

                var work = DatabaseConnector.GetWhere<Work>($"WorkSetID={set.WorksetID}");

                // Shuffle the work if it is supposed to be in a random order.
                if (set.RandomOrdering)
                    work.Shuffle();

                // Create the question set.
                QuestionSets qSet = new QuestionSets()
                {
                    UserID = uid,
                    WorkSetID = WorkSetID,
                    Date_Asked = DateTime.Today
                };

                // Save to the datbase and get the ID of the question set
                qSet.QuestionSetID = DatabaseConnector.AddQuestionSet(qSet);

                List<QuestionViewModel> Qusts = new List<QuestionViewModel>();

                // Go through each piece of required work and update and save it.
                foreach (var piece in work)
                {
                    // Generate the seed for the question
                    var seed = StoredQuestion.GenerateSeed(piece.Seed);

                    // Create the question and save it to the database.
                    Questions qust = new Questions()
                    {
                        QuestionSetID = qSet.QuestionSetID,
                        Question_Type = piece.QuestionType,
                        Difficulty = (int)piece.Difficulty,
                        Seed = seed,
                        AnswerCorrect = 0
                    };
                    qust.QuestionID = DatabaseConnector.AddQuestion(qust);

                    // Gets the question informataion from the databse (the python file) and passes it into the pythond interpreter.
                    var curQuest = Interpreter.GenerateQuestion(AppContext.BaseDirectory + @"wwwroot\lib\Python\"
                        + DatabaseConnector.Get<QuestionTypes>().SingleOrDefault(x => x.TypeID == qust.Question_Type).Class, seed);

                    // From the scriptOuput get the names of the boxes and the hints for them
                    var boxes = curQuest.Boxes().Split(',');
                    var Hints = new List<string>();
                    Hints.AddRange(curQuest.Hints.Split(','));

                    //If we don't int for each box add some blank ones.
                    for (int i = Hints.Count - 1; i < boxes.Length; i++)
                    {
                        Hints.Add("");
                    }

                    // Create the question view model for the question set
                    var questionSet = new QuestionViewModel()
                    {
                        questionID = qust.QuestionID,
                        question = curQuest,
                        answer = new string[boxes.Length],
                        correct = new int[boxes.Length],
                        Hints = Hints.ToArray(),
                        Boxes = boxes
                    };
                    //Add it to the list of questions.
                    Qusts.Add(questionSet);

                    // Add the answer into the Http session to get the 
                    HttpContext.Session.Set("Q" + qust.QuestionID, Encoding.UTF8.GetBytes(questionSet.question.GetAnswer().ToString()));
                }
                // Return the entire question set 
                return View(new QuestionSetViewModel()
                {
                    QuestionSetID = qSet.QuestionSetID,
                    PerQuestion = (set.SetType == 1),
                    questions = Qusts.ToArray()
                });
            }
            return Unauthorized();
        }

        /// <summary>
        /// this will delete a workset and all matched information
        /// including any quesion sets that may have been created from it
        /// and all the work and questions from it.
        /// </summary>
        /// <param name="setID"></param>
        /// <returns></returns>
        public IActionResult Delete(int setID)
        {
            if (UserHelper.OwnsWorkset(UserHelper.GetUserId(HttpContext.Session), setID))
            {
                // Gets the questionsets with this ID
                var questionSets = DatabaseConnector.GetWhere<QuestionSets>($"WorkSetID={setID}");

                // Deletes all the questions from all of the question sets
                foreach (var qset in questionSets)
                {
                    DatabaseConnector.DeleteQuestions(qset.QuestionSetID);
                }
                // Deletes the question sets
                DatabaseConnector.DeleteQuestionSets(setID);

                // Gets the workset from that id
                var workset = DatabaseConnector.GetWorkset(setID);

                // Deletes all of the work from the worksets
                DatabaseConnector.DeleteWork(setID);

                //Informs the user what they have deleted
                string Name = workset.WorksetName + " - " + workset.WorksetID;

                // Deletes the workset
                DatabaseConnector.DeleteWorkset(setID);

                // Return the delete infomation.
                return View("Delete", Name);
            }
            return Unauthorized();
        }

        /// <summary>
        /// Gets the result of a workset using statistical modeling
        /// </summary>
        /// <param name="setID">the worksetid</param>
        /// <returns></returns>
        public IActionResult Results(int setID)
        {
            // Checjs that the user owns the workset
            if (UserHelper.OwnsWorkset(UserHelper.GetUserId(HttpContext.Session), setID))
            {
                GroupResultsViewModel model = new GroupResultsViewModel(setID);
                return View(model);
            }
            return Unauthorized();
        }

        /// <summary>
        /// When the user completes a workset give them information about the workset they just completed
        /// </summary>
        /// <param name="setID"></param>
        /// <returns></returns>
        public IActionResult Complete(int setID)
        {
            // Get the workset information and model.
            CompleteQuestionViewModel model = new CompleteQuestionViewModel(setID);

            return View(model);
        }

        /// <summary>
        /// This method opens the creation page of a new workset
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            // Checks if the user has the privilages to create a new workset
            if (UserHelper.UserInRole(UserHelper.GetUserId(HttpContext.Session), UserHelper.ROLE_TEACHER)
                || UserHelper.UserInRole(UserHelper.GetUserId(HttpContext.Session), UserHelper.ROLE_ADMIN))
            {
                // Creates the new createworkset model
                var Model = new CreateSetViewModel();

                // Gets the groups the teacher has access too from the database.
                Model.Groups = UserHelper.GetGroups(UserHelper.GetUserId(HttpContext.Session));
                return View(Model);
            }
            // Errors if they do not have access.
            return Unauthorized();
        }

        /// <summary>
        /// Gets the information about the workset that the user selected
        /// and then creates the database model of the workset
        /// which is then saved in the database.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(CreateSetViewModel model)
        {
            // Checks that valid model has been returned
            if (!ModelState.IsValid)
            {
                model.Groups = UserHelper.GetGroups(UserHelper.GetUserId(HttpContext.Session));
                return View(model);
            }

            // Creates the workset from the given information
            Worksets sets = new Worksets()
            {
                GroupID = model.GroupID,
                WorksetName = model.WorksetName,

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/Build.cshtml
@model BuildViewModel
@{
    ViewData["Title"] = "Build List";
}
<script>
    var i = @(Model.Work != null ? Model.Work.Length : 0);
    function allowDrop(ev) {
        ev.preventDefault();
    }

    function drag(ev, type, typeID, copy) {
        ev.dataTransfer.setData("text", ev.target.id);
        ev.dataTransfer.setData("copy", copy);
        ev.dataTransfer.setData("type", type);
        ev.dataTransfer.setData("id", typeID);
    }

    function drop(ev) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text");
        var copy = ev.dataTransfer.getData("copy");
        var type = ev.dataTransfer.getData("type");

        var node;

        if (copy == "true") {
            node = document.getElementById(data).cloneNode(true);
        } else {
            node = document.getElementById(data);
        }



        if (ev.target.parentNode == node.parentNode || ev.target == node.parentNode) return;

        node.id = i + "-question"

        var ele = document.createElement("input");
        ele.type = "hidden";
        ele.id = "Work_" + i + "__Seed";
        ele.name = "Work[" + i + "].Seed";
        if (copy == "true") {
            ele.value = 0;
        } else {
            ele.value = data;
        }
        ele.setAttribute("data-val", "true");
        ele.setAttribute("data-val-required", "This is Required");

        var eli = document.createElement("input");
        eli.type = "hidden";
        eli.id = "Work_" + i + "__TypeID";
        eli.name = "Work[" + i + "].TypeID";
        eli.value = ev.dataTransfer.getData("id", type);
        eli.setAttribute("data-val", "true");
        eli.setAttribute("data-val-required", "This is Required");

        document.getElementById("BuildForm").appendChild(ele);
        document.getElementById("BuildForm").appendChild(eli);

        i++;

        node.innerHTML = type + "-" + node.innerHTML + " " + "<a style=\"color:red\" onclick=\"deleteEle('" + node.id + "')\" href=\"#\">&times;</a>"
        if (ev.target.tagName.toLowerCase() == "div") {
            ev.target.appendChild(node)
        } else {
            ev.target.parentNode.appendChild(node)
        }
    }

    function deleteEle(id){
        document.getElementById(id).remove();
        var count = id.split('-')[0]
        document.getElementById("Work_" + count + "__Seed").remove();
        document.getElementById("Work_" + count + "__TypeID").remove();
    }
</script>

<div class="sidenav" style="padding-left: 7px">
    <div id="possibles" style="overflow-y:scroll; overflow-x:no-display; max-height:70%;">
            <partial name="_workSets" model = "@Model.createdWork" />
    </div>

    @if (Model.createdWork.SelectFromList)
    {
        <form asp-controller="Set" asp-action="UpdatePossibleQuestion" data-ajax="true" data-ajax-method="POST" data-ajax-update="#possibles" data-ajax-mode="replace" id="Questions--Form" method="post" novalidate="novalidate">
            <button class="btn btn-primary" type="submit">Refresh</button>
        </form>
    }
</div>
<h2>Build</h2>

<h4>Drag and drop elements below to add them to the worksheet</h4>
<div ondrop="drop(event)" ondragover="allowDrop(event)" style="min-height:100px; border:3px solid black; max-width:500px; padding:5px">
    @if (Model.Work != null && Model.Work.Length > 0)
    {
        for (int i = 0; i < Model.Work.Length; i++)
        {
            <p id="@(i*-1)">@Model.Work[i].TypeName-@Model.Work[i].Answer <a style="color:red" onclick="deleteEle('@(i*-1)')" href="#">&times;</a></p>
        }
    }
</div>
<br />
<form asp-controller="set" asp-action="build" id="BuildForm">
    @Html.HiddenFor(m => m.WorkSetID)
    <button type="submit" class="btn btn-primary">Finnish</button>
    @if (Model.Work != null && Model.Work.Length > 0)
    {
        for (int i = 0; i < Model.Work.Length; i++)
        {
            @Html.HiddenFor(m => m.Work[i].Seed)
            @Html.HiddenFor(m => m.Work[i].TypeID)
        }
    }
</form>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/Complete.cshtml
@model CompleteQuestionViewModel
@using static AutoQuestionGenerator.Helper.Extentions
@{
    ViewData["Title"] = "Complete";
}

@*var questionTypes =
        (from question in Model.Question
         select question.Type.Type_Name).ToList();
    questionTypes = questionTypes.Unique().ToList();*@


<h2>Complete</h2>
<div style="max-width: 50%; max-height:150px">
    <canvas id="CorrectPer" width="400" height="400"></canvas>
</div>

<div style="max-width: 50%; max-height:30%">
    <canvas id="CorrectByType" width="400" height="400"></canvas>
</div>
<script>
    var options = {
        maintainAspectRatio: false,
        spanGaps: false,
        elements: {
            line: {
                tension: 0.4
            }
        },
        plugins: {
            filler: {
                propagate: false
            }
        },
        scales: {
            xAxes: [{
                ticks: {
                    autoSkip: false,
                    maxRotation: 0
                }
            }],
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    };
    new Chart('CorrectPer', {
        type: 'horizontalBar',
        data: {
            labels: ['Percentage'],
            datasets: [{
                label: '%',
                data: [@Model.Percentage.Percentage],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.4)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    },

                    beginAtZero: true, 
                    min: 0,
                    max: 100
                }],
                xAxes: [{
                    ticks: {
                        beginAtZero: true,
                        min: 0,
                        max: 100
                    }
                }]
            },
            maintainAspectRatio: false
        }
    });

    var ctx = document.getElementById("CorrectByType");
            var myChart = new Chart(ctx, {

                type: 'bar',
                data: {

                    labels: [@foreach (var item in Model.questionTypes)
            {

                        <text>'@item',</text>
            }],
            datasets: [{
            label: '% of Answers Correct',
                data: [@Model.List.Select(x => x.Percentage).ToList().Connect(","),2,3,4,5],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.4)',
                    'rgba(54, 162, 235, 0.4)',
                    'rgba(255, 206, 86, 0.4)',
                    'rgba(75, 192, 192, 0.4)',
                    'rgba(153, 102, 255, 0.4)',
                    'rgba(255, 159, 64, 0.4)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    },

                    min: 0,
                    max: 100
                }],
                xAxes: [{
                    min: 0,
                    max: 100
                }]
            }
        }
    });
</script>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/Create.cshtml
@model CreateSetViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create New Question Set</h2>
<br />
<div id="pageSelector">
    <form asp-action="Create" method="post" id="CreationForm">
        <div class="form-group" style="max-width:400px">
            Workset Name:
            @Html.TextBoxFor(m => m.WorksetName, new { @class = "form-control" })
            <div class="checkbox">
                <label>
                    @Html.CheckBoxFor(m => m.SelectFromList) Select questions and give them set answers?
                </label>
            </div>
            <div class="checkbox">
                <label>
                    @Html.CheckBoxFor(m => m.RandomQuestions) Randomise Question Order
                </label>
            </div>
            @Html.DropDownListFor(m => m.SetType, new SelectList(CreateSetViewModel.SetTypes, "SetType_ID", "SetType_Name"), new { @class = "form-control" })
            <br />
            @Html.DropDownListFor(m => m.GroupID, new SelectList(Model.Groups, "GroupID", "Group_Name"), new { @class = "form-control", onchange = "GroupSelectorOnChange()", id = "groupSelector" })
            <br />
            Time allowed (in minutes):
            @Html.TextBoxFor(m => m.TimeAllowed, new { @class = "form-control", type = "number", title="Leave at 0 to allow infinate time!"})
            <br />
            Due Date:
            @Html.TextBoxFor(m => m.Date_Due, new { @class = "form-control", type = "date" })
        </div>
        <button class="btn btn-primary" type="button" onclick="NextClick('CreationForm')" id="nextButton">Next</button>
    </form>
</div>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/Delete.cshtml
@model string
@{
    ViewData["Title"] = "Delete";
}

<h2>Deleted workset - @Model</h2>

<a href="~/work/set">Return to Worksets</a>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/Index.cshtml
@model QuestionSetViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
@if (!Model.PerQuestion)
{
    <div id="Question-Form">
        <partial name="_FullSet" model="@Model" />
    </div>
}
else
{
    @foreach (var Question in Model.questions)
    {

        <div id="Question:@Question.question.GetQuestion()">
            <p>Q: @Question.question.GetQuestion() </p>
            <form asp-controller="Set" asp-action="Checkquestion" data-ajax="true" data-ajax-method="POST" data-ajax-update="#answer-@Question.questionID" data-ajax-mode="replace" id="Question-@Question.questionID-Form" method="post" novalidate="novalidate" autocomplete="off">
                <div id="answer-@Question.questionID">
                    <partial name="_Question" model="@Question" />
                </div>
            </form>
        </div>
        <br />
    }
    <br />
    <button type="submit" class="btn btn-primary" onclick="window.location='/Set/Complete?setID=@Model.QuestionSetID'">Complete</button>
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/_FullSet.cshtml
@model QuestionSetViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-controller="Set" asp-action="Checkworkset" data-ajax="true" data-ajax-method="POST" data-ajax-update="#Question-Form" data-ajax-mode="replace" id="Questions" method="post" novalidate="novalidate" autocomplete="off">
    @Html.HiddenFor(m => m.QuestionSetID)
    @{ int correct = 0; }
    @for (int i = 0; i < Model.questions.Length; i++)
    {
        <div id="Question:@Model.questions[i].question.GetQuestion()">
            <p>Q: @Model.questions[i].question.GetQuestion() </p>
            <div id="answer-@Model.questions[i].questionID">
                @if (Model.questions[i].answer.Length == 1)
                {
                    <div class="row">
                        <div class="col-md-1">
                            Answer:
                        </div>
                        <div class="col-md-3">
                            @Html.TextBoxFor(m => m.questions[i].answer[0], new { style = (Model.questions[i].correct[0] < 0 ? "background:#FF0000" : (Model.questions[i].correct[0] > 0 ? "background:#0F0" : "background:#FFF")), placeholder = Model.questions[i].Hints[0], @class = "form-control" })
                        </div>
                    </div>
                    @Html.HiddenFor(m => m.questions[i].questionID)
                    @if (Model.questions[i].correct[0] < 0)
                    {
                        correct++;
                    }
                }
                else
                {
                    for (int q = 0; q < Model.questions[i].Boxes.Length; q++)
                    {
                        <div class="row">
                            <div class="col-md-1">
                                @Model.questions[i].Boxes[q]:
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m.questions[i].answer[q], new { style = (Model.questions[i].correct[q] < 0 ? "background:#FF0000" : (Model.questions[i].correct[q] > 0 ? "background:#0F0" : "background:#FFF")), placeholder = Model.questions[i].Hints[q], @class="form-control" })
                            </div>
                        </div>
                        @Html.HiddenFor(m => m.questions[i].questionID)

                    }
                    @if (Model.questions[i].correct.Where(x => x <= 0).Count() == 0)
                    {
                        correct++;
                    }
                }
            </div>
        </div>
        <br />
    }
    @if (correct == Model.questions.Length - 1)
    {
        <button type="button" onclick="window.location='/Set/Complete?setIDt=@Model.QuestionSetID';">Review</button>
    }
    else
    {
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="button" onclick="window.location='/Set/Complete?setID=@Model.QuestionSetID';">Quit & Review</button>
    }
</form>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/_Question.cshtml
@model QuestionViewModel
@Html.HiddenFor(m => m.questionID)
@if (Model.Boxes.Length <= 1)
{
    <div class="row">
        <div class="col-md-1">
            Answer:
        </div>
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.answer[0], new { style = (Model.correct[0] < 0 ? "background:#FF0000" : (Model.correct[0] > 0 ? "background:#0F0" : "background:#FFF")), placeholder = Model.Hints[0], @class = "form-control" })
        </div>
    </div><br />
    @Html.HiddenFor(m => m.Boxes[0])@Html.HiddenFor(m => m.Hints[0])
    @if (Model.correct[0] <= 0)
    {
        <button type="submit" class="btn">Submit</button>
    }
}
else
{
    for (int i = 0; i < Model.Boxes.Length; i++)
    {
        @Html.HiddenFor(x => x.Boxes[i])
        @Html.HiddenFor(x => x.Hints[i])
        <div class="row">
            <div class="col-md-1">
                @Model.Boxes[i]:
            </div>
            <div class="col-md-3"> 
                @Html.TextBoxFor(m => m.answer[i], new { style = (Model.correct[i] < 0 ? "background:#FF0000" : (Model.correct[i] > 0 ? "background:#0F0" : "background:#FFF")), placeholder = Model.Hints[i], @class="form-control" })
            </div>
        </div>
    }

    @if (Model.correct.Where(x => x <= 0).Count() > 0)
    {
        <button type="submit" class="btn">Submit</button>
    }
}
<br />

AutoQuestionGenerator/AutoQuestionGenerator/Views/Set/_workSets.cshtml
@model CreatedWork

@{ int i = 0; }


@foreach (var catagoryType in Model.CatagoryTypes)
{
    <div style="border: 2px solid black">
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#@catagoryType.CatTypeName.Replace(" ", "--")"
                style="background-color: Transparent;
background-repeat:no-repeat;
border: none;
cursor:pointer;
overflow: hidden;">
            &raquo; @catagoryType.CatTypeName
        </button>
        <div id="@catagoryType.CatTypeName.Replace(" ", "--")" class="collapse">
            @foreach (var catagory in catagoryType.Catagories)
            {
                <div style="border: 2px solid navy">
                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#@catagory.catagoryName.Replace(" ", "--")"
                            style="background-color: Transparent;
background-repeat:no-repeat;
border: none;
cursor:pointer;
overflow: hidden;">
                        &raquo; @catagory.catagoryName
                    </button>
                    <div id="@catagory.catagoryName.Replace(" ", "--")" class="collapse">
                        @foreach (var piece in catagory.WorkTypes)
                        {
                            if (Model.SelectFromList)
                            {
                                <div style="border-top: 3px solid black">
                                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#@piece.WorkType.Replace(" ", "--")"
                                            style="background-color: Transparent;
background-repeat:no-repeat;
border: none;
cursor:pointer;
overflow: hidden;">
                                        &raquo; @piece.WorkType
                                    </button>
                                    <div id="@piece.WorkType.Replace(" ", "--")" class="collapse">
                                        <h5 style="color:darkblue" title="Click Refresh for more">Possible Questions</h5>
                                        @foreach (var genWork in piece.PossibleWork)
                                        {
                                            <div ondragover="allowDrop(event)">
                                                <p draggable="true" id="@genWork.Seed" ondragstart="drag(event, '@piece.WorkType', @piece.TypeID, false)">@genWork.Answer</p>
                                            </div>
                                        }
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div ondragover="allowDrop(event)">
                                    <p draggable="true" id="@i" ondragstart="drag(event, '', @piece.TypeID,true)">@piece.WorkType</p>
                                    @{i++;}
                                </div>
                            }
                        }

                    </div>
                </div>
            }

        </div>
    </div>
}