AutoQuestionGenerator/AutoQuestionGenerator/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoQuestionGenerator.Models
{
    public class LoginViewModel
    {
        public string Organisation { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Error { get; set; }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Controllers/OrganisationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoQuestionGenerator.Accounts;
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.Helper;
using AutoQuestionGenerator.Models;
using AutoQuestionGenerator.Models.Hubs;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AutoQuestionGenerator.Controllers
{
    /// <summary>
    /// This controller deals with all the organisation information
    /// and many of the admin tasks to do with this.
    /// </summary>
    public class OrganisationController : Controller
    {
        IHostingEnvironment _env;

        public OrganisationController(IHostingEnvironment env)
        {
            _env = env;
        }

        /// <summary>
        /// This gerts most of the organisation details and returns them to the user
        /// so they can see the name and username of the organisation they are in
        /// More useful for the admins who can see details about the organisations subscription.
        /// </summary>
        /// <returns>The index page of the site</returns>
        public IActionResult Index()
        {
            return View(OrganisationHelper.GetOrganisation(HttpContext.Session));
        }

        /// <summary>
        /// Returns the organisation LoginPage
        /// 
        /// Now DEPRECATED as I moved to 1 page.
        /// </summary>
        /// <returns></returns>
        [Obsolete]
        public IActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// Returns information about the organistions users
        /// to an admin within that organisation.
        /// </summary>
        /// <returns>Users pages with information about the users</returns>
        public IActionResult Users()
        {
            var uid = UserHelper.GetUserId(HttpContext.Session);
            if (UserHelper.UserInRole(uid, UserHelper.ROLE_ADMIN))
            {
                return View(DatabaseConnector.GetUsers(UserHelper.GetUser(uid).OrganisationID));
            }
            return Unauthorized();
        }

        /// <summary>
        /// Lets the admin create a single new user
        /// this just loads the page.
        /// </summary>
        /// <returns></returns>
        public IActionResult CreateUser()
        {
            //Checks if the user trying to access this is an admin.
            if (UserHelper.UserInRole(UserHelper.GetUserId(HttpContext.Session), UserHelper.ROLE_ADMIN))
                return View();

            //They are not an admin give them an error.
            return Unauthorized();
        }

        /// <summary>
        /// This method take in the post information from the 
        /// website and uses it to create a new user.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult CreateUser(Users user)
        {
            //Check to see if the user trying to do this is an admin
            var uid = UserHelper.GetUserId(HttpContext.Session);
            if (UserHelper.UserInRole(uid, UserHelper.ROLE_ADMIN))
            {
                //Get the id of the organisation
                var organisation = UserHelper.GetUser(uid).OrganisationID;
                user.OrganisationID = organisation;

                //Check that user doesn't aready exist in this organisation
                var dbuser = UserHelper.GetUser(user.Username, organisation);
                if (!ModelState.IsValid || dbuser != null)
                    return View(user);

                //Create the new user if this is ppossible
                UserHelper.CreateNewUser(user.Username, organisation, user.Password, user.First_Name, user.Last_Name);
                return RedirectToAction("Users");
            }

            // The user is not authorised to do this so error.
            return Unauthorized();
        }

        /// <summary>
        /// Retuns the get view of the page which allows users to be uploaded to the website using a CSV
        /// This page is then returned by the user with the documents they with to upload.
        /// </summary>
        /// <returns></returns>
        public IActionResult UploadUsers()
        {
            if (UserHelper.UserInRole(UserHelper.GetUserId(HttpContext.Session), UserHelper.ROLE_ADMIN))
            {
                return View();
            }
            return Unauthorized();
        }

        /// <summary>
        /// The post form for uploading users
        /// this will then covert the files and save them, it will then parse
        /// them using some code to convert the csv into databas users.
        /// </summary>
        /// <param name="files">files from the upload</param>
        /// <returns>redirect to errors</returns>
        [HttpPost]
        public async Task<IActionResult> UploadUsers(List<IFormFile> files)
        {
            // Check if the user it authorised to make this action.
            if (UserHelper.UserInRole(UserHelper.GetUserId(HttpContext.Session), UserHelper.ROLE_ADMIN))
            {
                // Makes sure the upload directory exists
                Directory.CreateDirectory(Path.Combine(_env.WebRootPath, "lib/Excel/"));
                long size = files.Sum(f => f.Length);

                //Initialises the dictionaries we need to kepp track of the files.
                Dictionary<int, string> diction = new Dictionary<int, string>();
                Dictionary<int, FileInfo> file = new Dictionary<int, FileInfo>();

                int i = 0;
                //Iterates through each file.
                foreach (var formFile in files)
                {
                    //Checks the file is not length 0
                    if (formFile.Length > 0)
                    {
                        //Creates file info for the file
                        var f = new FileInfo(formFile.FileName);

                        //Gets the path too and generates a tempeorary file.
                        var filePath = Path.GetTempFileName() + f.Extension;
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            //Copies in the file information.
                            await formFile.CopyToAsync(stream);
                        }
                        // Adds the file information to the dictionaries
                        diction.Add(i, formFile.FileName);
                        file.Add(i, new FileInfo(filePath));
                        // Adds 1 to the nu
                        i++;
                    }
                }

                // Parses the files and saves to the DB
                List<string> ret = UserFiles(file);

                // Returns information about the parse.
                return View("NewUsers", ret.ToArray());
            }
            return Unauthorized();
        }

        /// <summary>
        /// This method iterates through each of the possible files
        /// and parses them one by one.
        /// </summary>
        /// <param name="files">The files with are being parsed</param>
        /// <returns>the information about the parse</returns>
        private List<string> UserFiles(Dictionary<int, FileInfo> files)
        {
            List<string> output = new List<string>();
            //Iterate through each file.
            foreach (var item in files)
            {
                //Test and setup that file.
                output.AddRange(ParseFile(item));
            }
            return output;
        }

        /// <summary>
        /// This method parses either a CSV
        /// or a Excel(xls(x)) file into the database and is able to add
        /// new users based on the information within those files.
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        private List<string> ParseFile(KeyValuePair<int, FileInfo> item)
        {
            // Checks whether the gile is an Excel file
            if (item.Value.Extension.ToLower().Contains("xls"))
            {
                try
                {
                    //Using Excel convert and save the file as a csv
                    Microsoft.Office.Interop.Excel.Application app = new Microsoft.Office.Interop.Excel.ApplicationClass();
                    Microsoft.Office.Interop.Excel.Workbook wbWorkbook = app.Workbooks.Open(item.Value.FullName);
                    wbWorkbook.SaveAs(Path.Combine(_env.WebRootPath, "lib/Excel/" + item.Value.Name) + ".csv", Microsoft.Office.Interop.Excel.XlFileFormat.xlCSV);
                    wbWorkbook.Close();

                    // Save the CSV and replace the file info object.
                    item = new KeyValuePair<int, FileInfo>(item.Key, new FileInfo(Path.Combine(_env.WebRootPath, "lib/Excel/" + item.Value.Name) + ".csv"));
                }
                // Error would occur if the file was in an ureadable format or did not upload correctly.
                catch (Exception)
                {
                    // Tell the user what went wrong with this file.
                    return new List<string>()
                    {
                        "Failed to convert workbook into CSV"
                    };
                }
            }

            // Check if the item is listed as a CSV
            if (item.Value.Extension.ToLower().Contains("csv"))
            {
                // Setup a list of possible error or information
                List<string> Information = new List<string>();

                //Open the file in steam.
                using (var stream = new StreamReader(new FileStream(item.Value.FullName, FileMode.Open)))
                {

AutoQuestionGenerator/AutoQuestionGenerator/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoQuestionGenerator.Accounts;
using AutoQuestionGenerator.DatabaseModels;
using AutoQuestionGenerator.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutoQuestionGenerator.Controllers
{
    public class UserController : Controller
    {
        public UserController()
        {
        }

        public IActionResult Delete(int id)
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel user, string returnUrl)
        {
            var DbOrganisation = DatabaseConnector.Get<Organisations>().FirstOrDefault(x => x.Organisation_Username == user.Organisation);
            if (!ModelState.IsValid || DbOrganisation == null)
            {
                if (DbOrganisation == null)
                {
                    user.Error = "Organisation does not exist.";
                    return View(user);
                }
                return View(user);
            }
            var DbUser = UserHelper.GetUser(user.Username, DbOrganisation.OrganisationID);
            if (DbUser == null)
            {
                user.Error = "Username or password incorrect.";
                return View(user);
            }

            if (DbUser.OrganisationID != DbOrganisation.OrganisationID)
            {
                user.Error = "Organisation is incorrect";
                return View(user);
            }

            if (Hasher.ValidatePassword(user.Password, DbUser.Password))
            {
                HttpContext.Session.Set("OrgId", Encoding.UTF8.GetBytes(DbOrganisation.OrganisationID.ToString()));
                HttpContext.Session.Set("Org_Uname", Encoding.UTF8.GetBytes(DbOrganisation.Organisation_Name));
                HttpContext.Session.Set(UserHelper.SESSION_UID, Encoding.UTF8.GetBytes(DbUser.UserID.ToString()));
                HttpContext.Session.Set("Username", Encoding.UTF8.GetBytes(user.Username));
                DbUser.Last_Logged_In = DateTime.Now;
                DatabaseConnector.Update(DbUser);
                DatabaseConnector.PushChanges();
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                user.Error = "Username or password incorrect.";
                return View(user);
            }
        }

        public IActionResult Logout(string returnUrl)
        {
            UserHelper.LogOut(HttpContext.Session);
            OrganisationHelper.LogOut(HttpContext.Session);
            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Lost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Lost(LoginViewModel user)
        {
            var DbOrganisation = DatabaseConnector.Get<Organisations>().FirstOrDefault(x => x.Organisation_Username == user.Organisation);
            if (!ModelState.IsValid || DbOrganisation == null)
            {
                return View(user);
            }
            var DbUser = UserHelper.GetUser(user.Username, DbOrganisation.OrganisationID);

            if (!ModelState.IsValid || DbUser == null) return View(user);

            DbUser.Password = Hasher.Hash(user.Password);
            DatabaseConnector.Update(DbUser);
            DatabaseConnector.PushChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/CreateUser.cshtml
@model AutoQuestionGenerator.DatabaseModels.Users

@{
    ViewData["Title"] = "CreateUser";
}

<h2>CreateUser</h2>

<h4>Users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser" asp-antiforgery="true">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="First_Name" class="control-label"></label>
                <input asp-for="First_Name" class="form-control" />
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" class="control-label"></label>
                <input asp-for="Last_Name" class="form-control" />
                <span asp-validation-for="Last_Name" class="text-danger"></span>
            </div>
            @if (Model != null && !string.IsNullOrWhiteSpace(Model.Username))
            {
                <p style="color: red">User already exists in the database</p>
            }
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/Index.cshtml
@model AutoQuestionGenerator.DatabaseModels.Organisations
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<br /><br />
<h3>Info</h3>
<p>
    ID: @Model.OrganisationID <br />
    Name: @Model.Organisation_Name <br />
    Username: @Model.Organisation_Username <br />
</p>
<br />
@if (AutoQuestionGenerator.Accounts.UserHelper.UserInRole(AutoQuestionGenerator.Accounts.UserHelper.GetUserId(HttpContextAccessor.HttpContext.Session), AutoQuestionGenerator.Accounts.UserHelper.ROLE_ADMIN, new AutoQuestionGenerator.DatabaseModels.IdentityModels()))
{
    <p>
        Subscription Type: @Model.Subscription_Type<br />
        Next Renewal Date: @Model.Subscription_Renew_Date
    </p>
    <div class="row">
        <div class="col-md-offset-1 col-md-2">
            <form asp-action="Users" method="get">
                <button type="submit" class="btn">User Informaion</button>
            </form>
        </div>
        <div class="col-md-1">
            <form asp-action="Groups" method="get">
                <button type="submit" class="btn">Groups</button>
            </form>
        </div>
    </div>
    <form asp-action="Update">
<button type="submit" class="btn btn-danger">Update Details</button>
</form>
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/Login.cshtml
@model AutoQuestionGenerator.DatabaseModels.Organisations
@{
    ViewData["Title"] = "Login";
}

<h2>Organisation Login</h2>
<br />
<br />
@using (Html.BeginForm(FormMethod.Post, new
{
    autocomplete = "off"
}))
{
    <text>Username: @Html.TextBoxFor(m => m.Organisation_Username, new { autocomplete = "off" })</text><br /><br />
    <text>Password: @Html.TextBoxFor(m => m.Organisation_Password, new { type = "password", autocomplete = "off" })</text>
    <button type="submit" class="=btn btn-primary">Login</button>
    if (Model != null && !string.IsNullOrEmpty(Model.Organisation_Username))
    {
        <br />
        <p style="color:red">Username or password incorrect</p>
    }
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/Lost.cshtml
@model UpdateUser
@{
    ViewData["Title"] = "Lost";
}

<h2>Lost</h2>
<br />
@using (Html.BeginForm())
{
<table>
    <tr>
        <td>Enter Username:</td>
        <td>@Html.TextBoxFor(m => m.Username)</td>
    </tr>
    <tr>
        <td>New Password:</td>
        <td>@Html.TextBoxFor(m => m.Password, new { type = "password" })</td>
    </tr>
    <tr>
        <td>Re-enter Password:</td>
        <td>@Html.TextBoxFor(m => m.VerifyPassword, new { type = "password" })</td>
    </tr>
</table>
    <button type="submit" class="btn btn-primary">Login</button>
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/NewUsers.cshtml
@model string[]
@{
    ViewData["Title"] = "NewUsers";
}

<h2>New Users</h2>

<h4>Errors and information from the parse</h4>
<br />
<p>
    @foreach (var item in Model)
    {
    <div @(item.ToLower().Contains("failed") ? "style='color:red'" : "")>@item</div><br />
    }
</p>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/Reset.cshtml
@model UpdateUser
@{
    ViewData["Title"] = "Reset";
}

<h2>Reset</h2>
<br />
@using (Html.BeginForm())
{
<table>
    <tr>
        <td>Enter Old-password:</td>
        <td>@Html.TextBoxFor(m => m.Username, new { type = "password", id= "organisationOriginal" })</td>
    </tr>
    <tr>
        <td>New Password:</td>
        <td>@Html.TextBoxFor(m => m.Password, new { type = "password", id = "organisationPassword" })</td>
    </tr>
    <tr>
        <td>Re-enter Password:</td>
        <td>@Html.TextBoxFor(m => m.VerifyPassword, new { type = "password", id = "Password Reset" })</td>
    </tr>
</table>
    <button type="submit" class="btn btn-primary">Login</button>
}

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/Update.cshtml
@model AutoQuestionGenerator.DatabaseModels.Organisations
@{
    ViewData["Title"] = "Update";
}

<script>
    function Confirm() {
        var r = confirm("Are you sure you want to update these details as they are required for students to gain access?");
        if (r == true) {

        }
    }
</script>

<h2>Update Details</h2>

<form asp-action="Update">
    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-3">

        </div>
    </div>

    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-3">

        </div>
    </div>

    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-3">

        </div>
    </div>
</form>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/UploadUsers.cshtml
@{
    ViewData["Title"] = "UploadUsers";
}

<h2>UploadUsers</h2>
<br />
<p>
    Either upload an excel(XLS/XLSX) Or a CSV file. The headers of the file should include "firstname", "lastname", "username", "password" and one column for each "role" that the user has.
    These columns can be in any order. However the roles must be an exact copy of "admin", "teacher", or "student".
</p>
<form method="post" enctype="multipart/form-data" asp-controller="Organisation" asp-action="UploadUsers">
    <div class="form-group">
        <p>Upload one or more files for convertion to users using this form:</p>
        <input class="form-control" type="file" name="files" multiple />
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Upload" />
    </div>
</form>

AutoQuestionGenerator/AutoQuestionGenerator/Views/Organisation/Users.cshtml
@model AutoQuestionGenerator.DatabaseModels.Users[]
@{
    ViewData["Title"] = "Users";
}
<script>
    function Confirm(name, id) {
        var r = confirm("Are you sure you want to delete " + name);
        if (r == true) {
            location.href = "~/User/Delete?id=" + id
        }
    }
</script>
<h2>Users</h2>

<table id="UserTable">
    <tr>
        <th onclick="sortTable(0,'UserTable')">
            Username
        </th>
        <th onclick="sortTable(0,'UserTable')">Firstname</th>
        <th onclick="sortTable(0,'UserTable')">Lastname</th>
        <th onclick="sortTable(0,'UserTable')">Last Logged In</th>
        <th onclick="sortTable(0,'UserTable')">Edit / Delete</th>
    </tr>
    @for (int i = 0; i < Model.Length; i++)
    {
    <tr>
        <td>
            @Model[i].Username
        </td>
        <td>
            @Model[i].First_Name
        </td>
        <td>
            @Model[i].Last_Name
        </td>
        <td>
            @Model[i].Last_Logged_In
        </td>
        <td>
            <a href="~/User/Edit?ID=@Model[i].UserID">Edit</a>
            <a onclick="Confirm('@Model[i].First_Name @Model[i].Last_Name', @Model[i].UserID)" href="">Delete</a>
        </td>
    </tr>
    }
</table><br />
<div class="row">
    <div class="col-md-offset-1 col-md-3">

        <form asp-action="UploadUsers" method="get">
            <button type="submit" class="btn">Upload Multiple Users</button>
        </form>
        <br />
    </div>
    <div class="col-md-1">
        <form asp-action="CreateUser" method="get">
            <button type="submit" class="btn">Create New User</button>
        </form>
    </div>
</div>